#!/bin/bash

mydir="$(dirname $0)"
source $mydir/java-settings

CACHE_DIR="/var/cache/java-installer"
if [ ! -d "$CACHE_DIR" ]; then mkdir $CACHE_DIR; fi

jdkfile="$CACHE_DIR/$JDK_ARCHIVE"
if [ ! -f "$jdkfile" ]; then 
  curl -L -C - -b "oraclelicense=accept-securebackup-cookie" -o $jdkfile $JDK_LOCATION
fi
echo $jdkfile
